image: maven:latest

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -P headless -DskipUiTests=true"

stages:
  - build
  - test

build:
  stage: build
  script:
    - "cd booking; mvn clean install $MAVEN_CLI_OPTS"

test:
  stage: test
  script:
    - "cd booking; mvn clean test $MAVEN_CLI_OPTS"
