image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -P headless -DskipUiTests=true"

stages:
  - test
  - build

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

test:
  stage: test
  script:
    - "cd todolist; mvn clean test $MAVEN_CLI_OPTS"

build:
  stage: build
  when: manual
  script:
    - "cd todolist; mvn clean install $MAVEN_CLI_OPTS"
