image: maven:3.8.3-openjdk-17
stages:
  - build
  - test

build:
  stage: build
  script:
    # - "cd booking; mvn clean install -U --batch-mode -DskipUiTests=true"

test:
  stage: test
  script:
    # - "cd booking; mvn clean test -U --batch-mode -DskipUiTests=true"
